[project]
name = "argsortium-inference"
version = "0.1.0"
description = "Workflows and scripts to infer ARGs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "snakemake==9.13.3",
]
